### ISSUE TITLE
Broken ex5-ext version: published package is 0 bytes

### ISSUE THREAD

**Issue by stanhu** [medikoo/es5-ext#108]
https://www.npmjs.com/package/es5-ext shows:

![image](https://user-images.githubusercontent.com/963826/157106714-24d1f3c1-ee29-4267-a738-4def8794f6bb.png)

This is causing some installs to fail with `MODULE_NOT_FOUND`:

```
npm info lifecycle es5-ext@0.10.54~postinstall: es5-ext@0.10.54

> es5-ext@0.10.54 postinstall /root/.npm/_npx/5292/lib/node_modules/sass-lint/node_modules/es5-ext
> node ./_postinstall.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/5292/lib/node_modules/sass-lint/node_modules/es5-ext/_postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by stanhu** [comment]
Closing in favor of #109.
