### ISSUE TITLE
Cannot find module '../../object/valid-value' on npm install

### ISSUE THREAD

**Issue by zanona** [medikoo/es5-ext#33]
Hey guys, just bringing this issue from https://github.com/imagemin/imagemin/issues/104#issuecomment-110885706 since we found out it's coming from es5-ext, more precisely, the root cause is [this line](https://github.com/medikoo/es5-ext/blob/83b2182f67b1d213e4336772ed6b04f66f5e3550/array/%23/clear.js).

Thanks

---

I am not sure what is really happening but it usually to install fine from my CI environment, however now `npm install` is returning the following chain of errors. Any ideas?

```sh
> gifsicle@3.0.0 postinstall /home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

module.js:333
    throw err;
          ^
Error: Cannot find module '../../object/valid-value'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es5-ext/array/#/clear.js:7:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/polyfill.js:3:22)

> jpegtran-bin@3.0.1 postinstall /home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

module.js:333
    throw err;
          ^
Error: Cannot find module '../../object/valid-value'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es5-ext/array/#/clear.js:7:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0

> optipng-bin@3.0.2 postinstall /home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

module.js:333
    throw err;
          ^
Error: Cannot find module '../../object/valid-value'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/node_modules/es5-ext/array/#/clear.js:7:13)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/home/ubuntu/indigofx.co.uk/node_modules/pakku/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/es6-set/polyfill.js:3:22)
npm WARN optional dep failed, continuing imagemin-jpegtran@4.2.0
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
```

**Comment by medikoo** [comment]
@zanona I think there's something broken with you're installation. I'm not aware of any inconsistencies like that in es5-ext.

If you're still sure it's problem of es5-ext, then please let me know exact steps to reproduce that issues.

**Comment by greypants** [comment]
I'm having the same issue on Circle CI. The only thing I can think of is maaaaybe `#` isn't a valid folder name on whatever server setup Circle CI is using, and that's causing the `Error: Cannot find module '../../object/valid-value'` from `array/#/clear.js` Other than that, I don't know why it wouldn't resolve that path.

**Comment by medikoo** [comment]
@greypants if it would be problem of '#' folder being stripped, then it would rather be module at some '#' path that can't be loaded.

Here you have existing module at `es5-ext/array/#/clear.js` which tries to import `es5-ext/object/valid-value` which doesn't exist. So it's not the case of missing `#` folder.

This is evident issue with given setup, there was no es5-ext version which would expose such inconsistency.

**Comment by zanona** [comment]
@greypants I was having the same problem on CircleCI as well. Updating imagemin to the latest version and re-running the build process with clean cache seemed to work for me?

**Comment by frgtn** [comment]
I'm also having similar issues, this time with CycleJS and jspm. Any suggestions on best approach to debug this?

**Comment by zanona** [comment]
@frgtn I have been able to debug this via building with support to SSH on CircleCI.
In the end, upgrading imagemin and nodejs to the latest version have worked there for me.

**Comment by WorldMaker** [comment]
I've also been trying to get CycleJS through JSPM. It definitely seems that either SystemJS and/or the browser can't up-folder through the `#` folder correctly. Given `#` does have special meaning in HTTP URLs, I'm wondering if either A) es5-ext should use a folder with a more URL friendly name that `#`, or B) es5-ext should not use relative imports from under `#` folders and instead should always use the full `require('es5-ext/object/valid-value')`, or even possibly C) have SystemJS specific shims. (Running in a SystemJS environment you should be able to rely on that fact that an ES6 polyfill such as Traceur or Babel is already loaded...)

**Comment by medikoo** [comment]
@WorldMaker CJS require paths are meant to be a valid system paths, not urls. If some utility tries to transport CJS modules over urls, its responsibility is to use proper [escaping](https://en.wikipedia.org/wiki/Percent-encoding). If utility you use doesn't do that, I suggest to report a bug over there.

es5-ext's usage of CJS is perfectly valid.
